CREATE DATABASE IF NOT EXISTS BD_EST_SUPER;
USE BD_EST_SUPER;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CPF_CNPJ VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    VALIDADE VARCHAR(100) NOT NULL, 
    EMBALAGEM VARCHAR(50),
    FK_ID_CATEGORIA INT,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) 
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PRODUTO INT,
    FK_CPF_CNPJ_FORNECEDOR VARCHAR(11),
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY (FK_CPF_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CPF_CNPJ)
); 