CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA; 

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    RITIMO VARCHAR(9) NOT NULL,
    ESTILO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL, 
    CAPA BLOB, 
    DURACAO TIME,
    FK_CPF_ARTISTA VARCHAR(100),
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF) 
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    OUVINTES VARCHAR(100),
    NOME VARCHAR(100) NOT NULL, 
    LETRA VARCHAR(1000), 
    DURACAO TIME,
    FK_ID_ALBUM INT, 
	FK_ID_GENERO INT, 
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID), 
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID) 
); 